language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: r+f7sBJl6BKZBxbU+dkG1Ze43rPx0LoiMAcGQ90lkIthjH5z0y/xvOU8O+TGRN00hCpzzaPjkheqWiTxSVQI7yYqoPu/LnEFPs0LtSxlAHqgUysLQQFpmxz/NYzq2s7ThHJ1wdkWem9Kh1RGlXS22XgFJur81KvTlQRH5cfdxJWwXVDrqhB/5YGlWYtVSp6IriM92Fl9CLq5EgFSX64iSzvkW2RnetHd7Wz9SIAgrhcPe56WNopqD+MoYNLMTA4g1KrtBrJL4I5ySu4kdpe8L4pNZWOe7oiSIptj6qlEJaL9nUM8EzEO6LHj00hoaQc6aQC6SrI0PSywn9u0eaqxAKA+3b/v4+czUrx+Gzuunu+8IKcMLaT7ANNY1tnlrjALtyqEW4K9QCwXCJiNzr9+MWSsud/EMYTLQt2cYW31yACsQg32fhopqnl4+UHelJzcM29+VpteaRr+DSN+vcBHQoXnmrXqBxNLMMyhAO9ckHyqZKOlzy/WDj7LRFadNhBJ4FMlf7ktDjPCEcihFiCGGGkENZyoDPxbI6Cm0jqPnZdBEIhI3/f4+zRs0NJGi6fM5pU8rtiKu9MtDci37Phi1FpmFangoeD3Mya1uq7eAWMUIAu18QE/eP/H1tlsFazJ92TFu5ArZhyIjiuzCc/RemoM994QAjJarf0D65WF3zg=
  app: dvops-pipeline
  edge: true
