language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: yLFyvNaYOwgagJKDHqgMGnCtKEMrTN51LloBsWDdBl0WPD09uerzj3XvERwYkSjiJLkHynUPg6R+46vZ/4ypC6LKUke3alWggGQ82iNox10icA82Gh0lDZGo4M5dXs+e0YU0+Y5/B2xy6t3zBX8t+2sA+ErwG+tG7qR7k9jSztrpdm3xjydluZ7TiXl819F+wov9tEUlz1Fjjwo48w2hkvjfaYPKqnrmmEpdoWEHyxZQdpz9ngicI/ZwqCo952tIuVuk5L/n7xefBGAqNqFOW57kCnyMtsiOYlHUXTIv/IOTPM+jDXDQ0r0V1Y2SAEDt8Oe8YyQL3IT2A35T0dm1mpzqxLQ2LCW1ctaa0QNWNHbZH4ytKP8Ntmr+fv2DMUXQJNttwzDr0ffY924pKxQfNPWFbY52F31mZjcGR7llFqt7OqyaZXPDJa61RiCnYzI+6YJCOqyPOfU1ys2qG5zPLFm3DTkVQSZ3kAy7g922PdcJoO+HQ1RgOHbHS1X88oVLPGztq/qY/XbyO3S1syaat1hKySveabm650kWETcjC9s1oEn9bYjxiF1wLy/8Eg9BwcaJ7M+vpIvFaVEjZjsBq1htAlLgnhtJgX/Dt0cPCSJzkJhUNQ1hur8PdK4vY26mHJGkcyR3L9DtW9RRlBAm1lxdNv9BfR6EhAvsnufERhQ=
  app: dvops-pipeline
  edge: true
